export const XTONE_ITEMS = [
  { id: 1, name: "Aged Clay", href: "", img: "/products/xtone_aged_clay.webp" },
  { id: 2, name: "Alpi Verde", href: "", img: "/products/xtone_alpi_verde.webp"},
  { id: 3, name: "Alpinus White", href: "", img: "/products/xtone_alpinus_white.webp"},
  { id: 4, name: "Amazonite", href: "", img: "/products/xtone_amazonite.webp"},
  { id: 5, name: "Aria White", href: "", img: "/products/xtone_aria_white.webp"},
  { id: 6, name: "Ars Beige", href: "", img: "/products/xtone_ars_beige.webp"},
  { id: 7, name: "Astana Grey", href: "", img: "/products/xtone_astana_grey.webp"},
  { id: 8, name: "Bianco Lasa", href: "", img: "/products/xtone_bianco_lasa.webp"},
  { id: 9, name: "Blue Roma", href: "", img: "/products/xtone_blue_roma.webp"},
  { id: 10, name: "Bottega Acero", href: "", img: "/products/xtone_bottega_acero.webp"},
  { id: 11, name: "Bottega Antracita", href: "", img: "/products/xtone_bottega_antracita.webp"},
  { id: 12, name: "Bottega Caliza", href: "", img: "/products/xtone_bottega_caliza.webp"},
  { id: 13, name: "Breccia Imperiale", href: "", img: "/products/xtone_breccia_imperiale.webp"},
  { id: 14, name: "Calacatta Antico", href: "", img: "/products/xtone_calacatta_antico.webp"},
  { id: 15, name: "Calacatta Gold", href: "", img: "/products/xtone_calacatta_gold.webp"},
  { id: 16, name: "Calacatta Green", href: "", img: "/products/xtone_calacatta_green.webp"},
  { id: 17, name: "Calacatta Viola", href: "", img: "/products/xtone_calacatta_viola.webp"},
  { id: 18, name: "Calatorao", href: "", img: "/products/xtone_calatorao.webp"},
  { id: 19, name: "Ele", href: "", img: "/products/xtone_ele.webp"},
  { id: 20, name: "Ewood Camel", href: "", img: "/products/xtone_ewood_camel.webp"},
  { id: 21, name: "Fiori di Bosco", href: "", img: "/products/xtone_fiori_di_bosco.webp"},
  { id: 22, name: "Glem White", href: "", img: "/products/xtone_glem_white.webp"},
  { id: 23, name: "Invisible White", href: "", img: "/products/xtone_invisible_white.webp"},
  { id: 24, name: "Liem Black", href: "", img: "/products/xtone_liem_black.webp"},
  { id: 25, name: "Liem Dark", href: "", img: "/products/xtone_liem_dark.webp"},
  { id: 26, name: "Liem Grey", href: "", img: "/products/xtone_liem_grey.webp"},
  { id: 27, name: "Montreal White", href: "", img: "/products/xtone_montreal_white.webp"},
  { id: 28, name: "Moon White", href: "", img: "/products/xtone_moon_white.webp"},
  { id: 29, name: "Navona", href: "", img: "/products/xtone_navona.webp"},
  { id: 30, name: "Neda", href: "", img: "/products/xtone_neda.webp"},
  { id: 31, name: "Nylo Noir", href: "", img: "/products/xtone_nylo_noir.webp"},
  { id: 32, name: "Orobico Dark", href: "", img: "/products/xtone_orobico_dark.webp"},
  { id: 33, name: "Paonazzo Biondo", href: "", img: "/products/xtone_paonazzo_biondo.webp"},
  { id: 34, name: "Pietra Sicilia", href: "", img: "/products/xtone_pietra_sicilia.webp"},
  { id: 35, name: "Port Laurent", href: "", img: "/products/xtone_port_laurent.webp"},
  { id: 36, name: "Solo Black", href: "", img: "/products/xtone_solo_black.webp"},
  { id: 37, name: "Statuario", href: "", img: "/products/xtone_statuario.webp"},
  { id: 38, name: "Tadelakt Grey", href: "", img: "/products/xtone_tadelakt_grey.webp"},
  { id: 39, name: "Tadelakt Sand", href: "", img: "/products/xtone_tadelakt_sand.webp"},
  { id: 40, name: "Tadelakt Smoke", href: "", img: "/products/xtone_tadelakt_smoke.webp"},
  { id: 41, name: "Taj Mahal", href: "", img: "/products/xtone_taj_mahal.webp"},
  { id: 42, name: "Tura", href: "", img: "/products/xtone_tura.webp"},
];
